pipeline:
  print_env:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  print_env2:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  print_env3:
    image: golang:1.10-alpine
    commands:
    - pwd
    - env
    - find .
    - sleep 30
    group: build

  pingpong:
    image: redis
    commands:
      - sleep 5
      - redis-cli -h redis ping
      - redis-cli -h redis set HELLO hello
      - redis-cli -h redis get HELLO

  build_container:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: banzaicloud/nodejs-example
    tags: "nandi-test"
    log: debug

services:
  redis:
    image: redis
    ports:
    - 6379
  mysql:
    image: mysql
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "joskapista"
  while:
    image: busybox
    commands:
    - sleep 1000
  
